"""update obligations and alerts tables

Revision ID: d08a855099d2
Revises: 4eb409ecf783
Create Date: 2025-09-02 12:29:37.238633

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d08a855099d2"
down_revision = "4eb409ecf783"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_obligation_pages_created_at"), table_name="obligation_pages")
    op.drop_table("obligation_pages")
    op.add_column("alerts", sa.Column("content_type", sa.String(), nullable=False))
    op.add_column("alerts", sa.Column("due_date", sa.DateTime(timezone=True), nullable=True))
    op.add_column("alerts", sa.Column("effective_date", sa.DateTime(timezone=True), nullable=True))
    op.add_column("alerts", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("alerts", sa.Column("regulatory_metadata", sa.JSON(), nullable=True))
    op.add_column("alerts", sa.Column("assigned_to", sa.Uuid(), nullable=True))
    op.add_column("alerts", sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("alerts", sa.Column("last_updated_by", sa.Uuid(), nullable=True))
    op.alter_column("alerts", "description", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_detected_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_obligation_id"), table_name="alerts")
    op.create_index(op.f("ix_alerts_assigned_to"), "alerts", ["assigned_to"], unique=False)
    op.create_index(op.f("ix_alerts_last_updated_by"), "alerts", ["last_updated_by"], unique=False)
    op.drop_constraint(op.f("alerts_obligation_id_fkey"), "alerts", type_="foreignkey")
    op.create_foreign_key(None, "alerts", "users", ["last_updated_by"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "alerts", "users", ["assigned_to"], ["id"], ondelete="SET NULL")
    op.drop_column("alerts", "resolved_at")
    op.drop_column("alerts", "reviewed_at")
    op.drop_column("alerts", "obligation_id")
    op.add_column("obligations", sa.Column("alert_id", sa.Uuid(), nullable=True))
    op.add_column("obligations", sa.Column("content_type", sa.String(), nullable=False))
    op.create_index(op.f("ix_obligations_alert_id"), "obligations", ["alert_id"], unique=False)
    op.create_foreign_key(None, "obligations", "alerts", ["alert_id"], ["id"], ondelete="SET NULL")
    op.drop_column("obligations", "detected_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "obligations",
        sa.Column("detected_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "obligations", type_="foreignkey")
    op.drop_index(op.f("ix_obligations_alert_id"), table_name="obligations")
    op.drop_column("obligations", "content_type")
    op.drop_column("obligations", "alert_id")
    op.add_column("alerts", sa.Column("obligation_id", sa.UUID(), autoincrement=False, nullable=True))
    op.add_column(
        "alerts", sa.Column("reviewed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.add_column(
        "alerts", sa.Column("resolved_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "alerts", type_="foreignkey")
    op.drop_constraint(None, "alerts", type_="foreignkey")
    op.create_foreign_key(
        op.f("alerts_obligation_id_fkey"), "alerts", "obligations", ["obligation_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_index(op.f("ix_alerts_last_updated_by"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_assigned_to"), table_name="alerts")
    op.create_index(op.f("ix_alerts_obligation_id"), "alerts", ["obligation_id"], unique=False)
    op.create_index(op.f("ix_alerts_detected_at"), "alerts", ["detected_at"], unique=False)
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.alter_column("alerts", "description", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
    op.drop_column("alerts", "last_updated_by")
    op.drop_column("alerts", "assigned_at")
    op.drop_column("alerts", "assigned_to")
    op.drop_column("alerts", "regulatory_metadata")
    op.drop_column("alerts", "completed_at")
    op.drop_column("alerts", "effective_date")
    op.drop_column("alerts", "due_date")
    op.drop_column("alerts", "content_type")
    op.create_table(
        "obligation_pages",
        sa.Column("obligation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("page_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["obligation_id"], ["obligations.id"], name=op.f("obligation_pages_obligation_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["monitored_pages.id"], name=op.f("obligation_pages_page_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("obligation_id", "page_id", name=op.f("uq_obligation_pages_obligation_id_page_id")),
    )
    op.create_index(op.f("ix_obligation_pages_created_at"), "obligation_pages", ["created_at"], unique=False)
    # ### end Alembic commands ###
