"""add obligations source foreign key

Revision ID: 4eb409ecf783
Revises: 0dff8782d535
Create Date: 2025-08-26 20:23:16.843527

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4eb409ecf783"
down_revision = "0dff8782d535"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("monitored_pages", sa.Column("last_monitored_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f("ix_monitored_pages_last_checked_at"), table_name="monitored_pages")
    op.create_index(
        op.f("ix_monitored_pages_last_monitored_at"), "monitored_pages", ["last_monitored_at"], unique=False
    )
    op.drop_column("monitored_pages", "last_checked_at")
    op.add_column("obligations", sa.Column("source_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_obligations_source_id"), "obligations", ["source_id"], unique=False)
    op.create_foreign_key(None, "obligations", "regulatory_sources", ["source_id"], ["id"], ondelete="CASCADE")
    op.add_column(
        "regulatory_sources", sa.Column("last_monitoring_started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "regulatory_sources", sa.Column("last_monitoring_completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_regulatory_sources_last_monitoring_completed_at"),
        "regulatory_sources",
        ["last_monitoring_completed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_regulatory_sources_last_monitoring_started_at"),
        "regulatory_sources",
        ["last_monitoring_started_at"],
        unique=False,
    )
    op.drop_column("regulatory_sources", "last_monitored_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "regulatory_sources",
        sa.Column("last_monitored_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_regulatory_sources_last_monitoring_started_at"), table_name="regulatory_sources")
    op.drop_index(op.f("ix_regulatory_sources_last_monitoring_completed_at"), table_name="regulatory_sources")
    op.drop_column("regulatory_sources", "last_monitoring_completed_at")
    op.drop_column("regulatory_sources", "last_monitoring_started_at")
    op.drop_constraint(None, "obligations", type_="foreignkey")
    op.drop_index(op.f("ix_obligations_source_id"), table_name="obligations")
    op.drop_column("obligations", "source_id")
    op.add_column(
        "monitored_pages",
        sa.Column("last_checked_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_monitored_pages_last_monitored_at"), table_name="monitored_pages")
    op.create_index(op.f("ix_monitored_pages_last_checked_at"), "monitored_pages", ["last_checked_at"], unique=False)
    op.drop_column("monitored_pages", "last_monitored_at")
    # ### end Alembic commands ###
