"""delete task_logs table

Revision ID: 61c646d81ba6
Revises: d0a99925f3c9
Create Date: 2025-11-18 19:20:05.763501

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "61c646d81ba6"
down_revision = "d0a99925f3c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_logs_created_at"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_started_at"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_status"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_task_id"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_task_name"), table_name="task_logs")
    op.drop_table("task_logs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("task_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("pending", "running", "completed", "failed", "cancelled", name="taskstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("progress", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("result_data", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("task_logs_pkey")),
    )
    op.create_index(op.f("ix_task_logs_task_name"), "task_logs", ["task_name"], unique=False)
    op.create_index(op.f("ix_task_logs_task_id"), "task_logs", ["task_id"], unique=True)
    op.create_index(op.f("ix_task_logs_status"), "task_logs", ["status"], unique=False)
    op.create_index(op.f("ix_task_logs_started_at"), "task_logs", ["started_at"], unique=False)
    op.create_index(op.f("ix_task_logs_created_at"), "task_logs", ["created_at"], unique=False)
    # ### end Alembic commands ###
