"""initial migration

Revision ID: 0dff8782d535
Revises:
Create Date: 2025-08-20 17:42:10.975613

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0dff8782d535"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("domains", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_created_at"), "organizations", ["created_at"], unique=False)
    op.create_index(op.f("ix_organizations_name"), "organizations", ["name"], unique=False)
    op.create_table(
        "task_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "completed", "failed", "cancelled", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("progress", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("result_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_logs_created_at"), "task_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_task_logs_started_at"), "task_logs", ["started_at"], unique=False)
    op.create_index(op.f("ix_task_logs_status"), "task_logs", ["status"], unique=False)
    op.create_index(op.f("ix_task_logs_task_id"), "task_logs", ["task_id"], unique=True)
    op.create_index(op.f("ix_task_logs_task_name"), "task_logs", ["task_name"], unique=False)
    op.create_table(
        "jurisdictions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jurisdictions_code"), "jurisdictions", ["code"], unique=False)
    op.create_index(op.f("ix_jurisdictions_created_at"), "jurisdictions", ["created_at"], unique=False)
    op.create_index(op.f("ix_jurisdictions_name"), "jurisdictions", ["name"], unique=False)
    op.create_index(op.f("ix_jurisdictions_organization_id"), "jurisdictions", ["organization_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_external_id"), "users", ["external_id"], unique=True)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "obligations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("obligation_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("risk_level", sa.Enum("high", "medium", "low", "unknown", name="risklevel"), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("regulatory_metadata", sa.JSON(), nullable=True),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["last_updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_obligations_assigned_to"), "obligations", ["assigned_to"], unique=False)
    op.create_index(op.f("ix_obligations_created_at"), "obligations", ["created_at"], unique=False)
    op.create_index(op.f("ix_obligations_last_updated_by"), "obligations", ["last_updated_by"], unique=False)
    op.create_index(op.f("ix_obligations_organization_id"), "obligations", ["organization_id"], unique=False)
    op.create_index(op.f("ix_obligations_risk_level"), "obligations", ["risk_level"], unique=False)
    op.create_index(op.f("ix_obligations_status"), "obligations", ["status"], unique=False)
    op.create_table(
        "regulatory_sources",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("jurisdiction_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("content_types", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("monitoring_enabled", sa.Boolean(), nullable=False),
        sa.Column("monitoring_frequency", sa.String(), nullable=False),
        sa.Column("last_monitored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["jurisdiction_id"], ["jurisdictions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_regulatory_sources_created_at"), "regulatory_sources", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_regulatory_sources_jurisdiction_id"), "regulatory_sources", ["jurisdiction_id"], unique=False
    )
    op.create_index(
        op.f("ix_regulatory_sources_monitoring_enabled"), "regulatory_sources", ["monitoring_enabled"], unique=False
    )
    op.create_index(
        op.f("ix_regulatory_sources_organization_id"), "regulatory_sources", ["organization_id"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("obligation_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("alert_type", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("risk_level", sa.Enum("high", "medium", "low", "unknown", name="risklevel"), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["obligation_id"], ["obligations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_created_at"), "alerts", ["created_at"], unique=False)
    op.create_index(op.f("ix_alerts_detected_at"), "alerts", ["detected_at"], unique=False)
    op.create_index(op.f("ix_alerts_obligation_id"), "alerts", ["obligation_id"], unique=False)
    op.create_index(op.f("ix_alerts_organization_id"), "alerts", ["organization_id"], unique=False)
    op.create_index(op.f("ix_alerts_risk_level"), "alerts", ["risk_level"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_table(
        "monitored_pages",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("url_hash", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("content_fingerprint", sa.String(), nullable=True),
        sa.Column("content_length", sa.BigInteger(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("risk_level", sa.Enum("high", "medium", "low", "unknown", name="risklevel"), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_code", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["regulatory_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_monitored_pages_created_at"), "monitored_pages", ["created_at"], unique=False)
    op.create_index(op.f("ix_monitored_pages_last_checked_at"), "monitored_pages", ["last_checked_at"], unique=False)
    op.create_index(op.f("ix_monitored_pages_organization_id"), "monitored_pages", ["organization_id"], unique=False)
    op.create_index(op.f("ix_monitored_pages_risk_level"), "monitored_pages", ["risk_level"], unique=False)
    op.create_index(op.f("ix_monitored_pages_source_id"), "monitored_pages", ["source_id"], unique=False)
    op.create_index(op.f("ix_monitored_pages_status"), "monitored_pages", ["status"], unique=False)
    op.create_index(op.f("ix_monitored_pages_url_hash"), "monitored_pages", ["url_hash"], unique=False)
    op.create_table(
        "task_runs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("task_run_type", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "completed", "failed", "cancelled", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("task_name", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=True, comment="Task run statistics and metrics"),
        sa.Column("extra_metadata", sa.JSON(), nullable=True, comment="Additional task run metadata"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["regulatory_sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_runs_completed_at"), "task_runs", ["completed_at"], unique=False)
    op.create_index(op.f("ix_task_runs_created_at"), "task_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_task_runs_organization_id"), "task_runs", ["organization_id"], unique=False)
    op.create_index(op.f("ix_task_runs_source_id"), "task_runs", ["source_id"], unique=False)
    op.create_index(op.f("ix_task_runs_started_at"), "task_runs", ["started_at"], unique=False)
    op.create_index(op.f("ix_task_runs_status"), "task_runs", ["status"], unique=False)
    op.create_index(op.f("ix_task_runs_task_id"), "task_runs", ["task_id"], unique=True)
    op.create_index(op.f("ix_task_runs_task_name"), "task_runs", ["task_name"], unique=False)
    op.create_index(op.f("ix_task_runs_task_run_type"), "task_runs", ["task_run_type"], unique=False)
    op.create_table(
        "alert_pages",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_id"], ["monitored_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alert_id", "page_id"),
        sa.UniqueConstraint("alert_id", "page_id", name="uq_alert_pages_alert_id_page_id"),
    )
    op.create_index(op.f("ix_alert_pages_created_at"), "alert_pages", ["created_at"], unique=False)
    op.create_table(
        "obligation_pages",
        sa.Column("obligation_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["obligation_id"], ["obligations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_id"], ["monitored_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("obligation_id", "page_id"),
        sa.UniqueConstraint("obligation_id", "page_id", name="uq_obligation_pages_obligation_id_page_id"),
    )
    op.create_index(op.f("ix_obligation_pages_created_at"), "obligation_pages", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_obligation_pages_created_at"), table_name="obligation_pages")
    op.drop_table("obligation_pages")
    op.drop_index(op.f("ix_alert_pages_created_at"), table_name="alert_pages")
    op.drop_table("alert_pages")
    op.drop_index(op.f("ix_task_runs_task_run_type"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_task_name"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_task_id"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_status"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_started_at"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_source_id"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_organization_id"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_created_at"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_completed_at"), table_name="task_runs")
    op.drop_table("task_runs")
    op.drop_index(op.f("ix_monitored_pages_url_hash"), table_name="monitored_pages")
    op.drop_index(op.f("ix_monitored_pages_status"), table_name="monitored_pages")
    op.drop_index(op.f("ix_monitored_pages_source_id"), table_name="monitored_pages")
    op.drop_index(op.f("ix_monitored_pages_risk_level"), table_name="monitored_pages")
    op.drop_index(op.f("ix_monitored_pages_organization_id"), table_name="monitored_pages")
    op.drop_index(op.f("ix_monitored_pages_last_checked_at"), table_name="monitored_pages")
    op.drop_index(op.f("ix_monitored_pages_created_at"), table_name="monitored_pages")
    op.drop_table("monitored_pages")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_risk_level"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_organization_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_obligation_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_detected_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_created_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_regulatory_sources_organization_id"), table_name="regulatory_sources")
    op.drop_index(op.f("ix_regulatory_sources_monitoring_enabled"), table_name="regulatory_sources")
    op.drop_index(op.f("ix_regulatory_sources_jurisdiction_id"), table_name="regulatory_sources")
    op.drop_index(op.f("ix_regulatory_sources_created_at"), table_name="regulatory_sources")
    op.drop_table("regulatory_sources")
    op.drop_index(op.f("ix_obligations_status"), table_name="obligations")
    op.drop_index(op.f("ix_obligations_risk_level"), table_name="obligations")
    op.drop_index(op.f("ix_obligations_organization_id"), table_name="obligations")
    op.drop_index(op.f("ix_obligations_last_updated_by"), table_name="obligations")
    op.drop_index(op.f("ix_obligations_created_at"), table_name="obligations")
    op.drop_index(op.f("ix_obligations_assigned_to"), table_name="obligations")
    op.drop_table("obligations")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_external_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_jurisdictions_organization_id"), table_name="jurisdictions")
    op.drop_index(op.f("ix_jurisdictions_name"), table_name="jurisdictions")
    op.drop_index(op.f("ix_jurisdictions_created_at"), table_name="jurisdictions")
    op.drop_index(op.f("ix_jurisdictions_code"), table_name="jurisdictions")
    op.drop_table("jurisdictions")
    op.drop_index(op.f("ix_task_logs_task_name"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_task_id"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_status"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_started_at"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_created_at"), table_name="task_logs")
    op.drop_table("task_logs")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_created_at"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
