"""update monitored pages table

Revision ID: e735fddc65ed
Revises: d08a855099d2
Create Date: 2025-09-04 16:55:41.571244

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e735fddc65ed"
down_revision = "d08a855099d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("source_id", sa.Uuid(), nullable=False))
    op.alter_column("alerts", "alert_type", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_content_type"), "alerts", ["content_type"], unique=False)
    op.create_index(op.f("ix_alerts_source_id"), "alerts", ["source_id"], unique=False)
    op.create_foreign_key(None, "alerts", "regulatory_sources", ["source_id"], ["id"], ondelete="CASCADE")
    op.add_column("monitored_pages", sa.Column("confidence", sa.Float(), nullable=False))
    op.add_column("monitored_pages", sa.Column("is_regulatory", sa.Boolean(), nullable=False))
    op.add_column("monitored_pages", sa.Column("content_types", sa.ARRAY(sa.Text()), nullable=False))
    op.add_column("monitored_pages", sa.Column("content_mime_type", sa.String(), nullable=True))
    op.drop_index(op.f("ix_monitored_pages_risk_level"), table_name="monitored_pages")
    op.drop_column("monitored_pages", "risk_level")
    op.drop_column("monitored_pages", "content_type")
    op.alter_column("obligations", "obligation_type", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_obligations_content_type"), "obligations", ["content_type"], unique=False)
    op.create_index(op.f("ix_obligations_obligation_type"), "obligations", ["obligation_type"], unique=False)
    op.alter_column("regulatory_sources", "content_types", existing_type=postgresql.ARRAY(sa.TEXT()), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("regulatory_sources", "content_types", existing_type=postgresql.ARRAY(sa.TEXT()), nullable=True)
    op.drop_index(op.f("ix_obligations_obligation_type"), table_name="obligations")
    op.drop_index(op.f("ix_obligations_content_type"), table_name="obligations")
    op.alter_column("obligations", "obligation_type", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column("monitored_pages", sa.Column("content_type", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        "monitored_pages",
        sa.Column(
            "risk_level",
            postgresql.ENUM("high", "medium", "low", "unknown", name="risklevel"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_monitored_pages_risk_level"), "monitored_pages", ["risk_level"], unique=False)
    op.drop_column("monitored_pages", "content_mime_type")
    op.drop_column("monitored_pages", "content_types")
    op.drop_column("monitored_pages", "is_regulatory")
    op.drop_column("monitored_pages", "confidence")
    op.drop_constraint(None, "alerts", type_="foreignkey")
    op.drop_index(op.f("ix_alerts_source_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_content_type"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.alter_column("alerts", "alert_type", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("alerts", "source_id")
    # ### end Alembic commands ###
