"""add_last_monitoring_scheduled_at_column_to_sources_table

Revision ID: dafd9f1fcdc1
Revises: a1b2c3d4e5f6
Create Date: 2025-11-19 16:11:06.388815

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dafd9f1fcdc1"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "regulatory_sources", sa.Column("last_monitoring_scheduled_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_regulatory_sources_last_monitoring_scheduled_at"),
        "regulatory_sources",
        ["last_monitoring_scheduled_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_regulatory_sources_last_monitoring_scheduled_at"), table_name="regulatory_sources")
    op.drop_column("regulatory_sources", "last_monitoring_scheduled_at")
    # ### end Alembic commands ###
