"""add indexes for search

Revision ID: d0a99925f3c9
Revises: e735fddc65ed
Create Date: 2025-10-17 21:40:27.815115

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d0a99925f3c9"
down_revision = "e735fddc65ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_alerts_title"), "alerts", ["title"], unique=False)
    op.create_index(op.f("ix_monitored_pages_title"), "monitored_pages", ["title"], unique=False)
    op.create_index(op.f("ix_monitored_pages_url"), "monitored_pages", ["url"], unique=False)
    op.create_index(op.f("ix_obligations_title"), "obligations", ["title"], unique=False)
    op.create_index(op.f("ix_regulatory_sources_base_url"), "regulatory_sources", ["base_url"], unique=False)
    op.create_index(op.f("ix_regulatory_sources_name"), "regulatory_sources", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_regulatory_sources_name"), table_name="regulatory_sources")
    op.drop_index(op.f("ix_regulatory_sources_base_url"), table_name="regulatory_sources")
    op.drop_index(op.f("ix_obligations_title"), table_name="obligations")
    op.drop_index(op.f("ix_monitored_pages_url"), table_name="monitored_pages")
    op.drop_index(op.f("ix_monitored_pages_title"), table_name="monitored_pages")
    op.drop_index(op.f("ix_alerts_title"), table_name="alerts")
    # ### end Alembic commands ###
